services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=dbOrder'
      - 'MYSQL_PASSWORD=freelancer'
      - 'MYSQL_ROOT_PASSWORD=freelancer'
    ports:
      - '3310:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
